version: "3.5"

services:
  postgres:
    container_name: ecommerce-database
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ecommerce
    volumes:
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "16543:5432"

volumes:
  ecommerce-api-database-volume:
    driver: local